Repository Kangdyu/i-ppendix, pull requests merged in 2022-05, with the labels that each got.

#7 feat: getTodo 기능 완성
  package-lock.json
  src/chrome/background.js
  src/chrome/getTodo.js
Labels: API

#6 feat: getNotice 기능 추가
  src/chrome/background.js
  src/chrome/getNotice.js
Labels: API

#8 feat: getCourseList getCourse 기능 추가
  src/chrome/background.js
  src/chrome/getCourse.js
Labels: API

#14 feat: todo 리스트 스타일링
  src/App.js
  src/chrome/mockup/todos.js
  src/components/PageContentContainer.js
  src/components/TodoList.js
  src/pages/CoursePage.js
  src/pages/HomePage.js
  src/utils/date.js
Labels: frontend

#19 fix: issue-getTodo 해결
  src/chrome/getTodo.js
Labels: API

#22 fix: getTodo에서 courseName을 진짜 수업 이름만 가져오도록 변경
  src/chrome/getTodo.js
Labels: API

#21 feat: todo list 기능 완성
  src/components/ContentCard.js
  src/components/Text.js
  src/components/TodoList.js
  src/pages/HomePage.js
  src/utils/constants.js
Labels: frontend

#25 feat: chrome icon button click & icon change
  public/i-ppendix-icon128.png
  public/index.html
  public/logo192.png
  public/logo512.png
  public/manifest.json
  src/chrome/background.js
Labels: chrome

#24 feat: readme작성 & feat: API 사용 전 쿠키검사
  README.md
  src/chrome/background.js
  src/chrome/getCookie.js
  src/chrome/getTodo.js
Labels: documentation, API

#26 feat: local storage 기능 추가
  public/manifest.json
  src/chrome/getCourse.js
Labels: API, chrome

#28 feat: 공지사항 및 공지사항 즐겨찾기 추가
  src/chrome/getCourse.js
  src/components/ContentCard.js
  src/components/NoticeList.js
  src/components/PageContentContainer.js
  src/components/Section.js
  src/components/TodoList.js
  src/hooks/useCourse.js
  src/hooks/useLocalStorageState.js
  src/hooks/useNotices.js
  src/pages/CoursePage.js
  src/pages/HomePage.js
  src/utils/constants.js
Labels: frontend

#29 fix: 하위 라우트에서 새로고침했을 시 페이지를 찾을 수 없는 문제 해결
  src/App.js
Labels: frontend

#30 feat: 메모 기능 구현
  src/components/MemoList.js
  src/components/NoticeList.js
  src/pages/HomePage.js
  src/utils/constants.js
Labels: frontend

#31 feat: 데이터 fetch 최적화
  src/chrome/getTodo.js
  src/index.js
  src/utils/constants.js
Labels: frontend, API

#32 docs: README.md 업데이트
  README.md
Labels: documentation
